analytics: {}
color:
  brandColors:
    - '#090909'
    - '#2d3236'
    - '#5d666e'
    - '#8a9dab'
    - '#adc0cf'
  brandStrength: 0.747747
  lightness: 0.583333
  rhythmicContrast: 0.635135
  saturation: 0.404279
cta: {}
layout_spectrum: 0.494369
name: Wandering monster
opengraph: {}
purpose: []
typography_spectrum: 0.57967
