name: null
favicon: null
layout_spectrum: 0.51423
typography_spectrum: 0.9329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5281d6'
    - '#29261c'
    - '#84ace9'
    - '#5a4f56'
    - '#f4dd9e'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
