analytics: {}
color:
  brandColors:
    - '#090909'
    - '#2d3236'
    - '#5d666e'
    - '#8a9dab'
    - '#adc0cf'
  brandStrength: 0.394144
  lightness: 0.118243
  rhythmicContrast: 0.309684
  saturation: 0.404279
cta: {}
layout_spectrum: 0.81081
name: Wandering monster
opengraph: {}
purpose: []
typography_spectrum: 0.57967
