name: null
favicon: null
layout_spectrum: 0.43896
typography_spectrum: 0.53164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#000000'
    - '#c3c3c3'
    - '#272727'
    - '#494949'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
