analytics: {}
color:
  brandColors:
    - '#090909'
    - '#2d3236'
    - '#5d666e'
    - '#8a9dab'
    - '#adc0cf'
  brandStrength: 0.5625
  lightness: 0.0625
  rhythmicContrast: 0.25
  saturation: 0.0625
cta: {}
layout_spectrum: 0.32017
name: Wandering monster
opengraph: {}
purpose: []
typography_spectrum: 0.57967
