name: Wandering monster
favicon: null
layout_spectrum: 0.5203
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#2d3236'
    - '#5d666e'
    - '#8a9dab'
    - '#adc0cf'
  brandStrength: 0.5625
  lightness: 0.0625
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
