analytics: {}
color:
  brandColors:
    - '#090909'
    - '#2d3236'
    - '#5d666e'
    - '#8a9dab'
    - '#adc0cf'
  brandStrength: 0.57545
  lightness: 0.066441
  rhythmicContrast: 0.666666
  saturation: 0.658783
cta: {}
layout_spectrum: 0.510135
name: Wandering monster
opengraph: {}
purpose: []
typography_spectrum: 0.57967
