name: Wandering monster
favicon: null
layout_spectrum: 0.31163
typography_spectrum: 0.57967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#2d3236'
    - '#5d666e'
    - '#8a9dab'
    - '#adc0cf'
  brandStrength: 0.394144
  lightness: 0.118243
  saturation: 0.404279
  rhythmicContrast: 0.309684
purpose: []
